### ISSUE TITLE
little issue with sintax color

### ISSUE THREAD

**Issue by juancarlosso** [EmranMR/tree-sitter-blade#26]
Works fine, but i am having this issue
[Screenshot](https://share.cleanshot.com/BjTZM8YL)
The color sintax looks all white, i am using the "Dark theme" (originally nova)
Is this normal or something i am not doing well ?

Thanks and keep the good work! 👍

**Comment by EmranMR** [comment]
Hi @juancarlosso, This is an issue with the [tree-sitter-php](https://github.com/EmranMR/tree-sitter-blade/issues/5#issue-1771613687)

Thankfully @CalebDW has already done the work and we are all [patiently awaiting for his pull request](https://github.com/tree-sitter/tree-sitter-php/pull/180#issue-1775188600) to be merged by the `tree-sitter-php` core team 😬. Once they merge, we should be good to go.

There is only one problem for us, and that is the fact Nova provides the `php` syntax support as a first party, and then we have to wait for them to update their `tree-sitter-php` parser... As a result I am going to see if I can clone the adjusted `tree-sitter-php` and override the ones provided by the Nova itself this weekend or so. Will be fun to see Nova blowing up 💥 because of conflicts and etc, considering there is no way for us to disable the built-in extensions... 😂

**Comment by EmranMR** [comment]
Hi @juancarlosso I would suggest upgrading your Nova extension to V1.0.0 which was released today 👀

**Comment by juancarlosso** [comment]
Excellent !
Thanks
