### ISSUE TITLE
Problem injecting php

### ISSUE THREAD

**Issue by EmranMR** [EmranMR/tree-sitter-blade#5]
All editors have an issue injecting `php`.
The problem arises because of the fact `php`parser has injection query for `html`.

Temporary fix ideas:
- try to fork php, and create a php-only tree-sitter parser with no injection.
- change the package.json to reflect

**Comment by CalebDW** [comment]
Instead of forking the repo and maintaining a separate copy of the original, the best thing to do would be to submit a PR to the original repo that splits into two different parsers, similar to the [markdown parser](https://github.com/MDeiml/tree-sitter-markdown) in which two parsers live in the same repo:


![image](https://github.com/EmranMR/tree-sitter-blade/assets/4176520/fed1b4b8-1047-49d1-b08a-b0acf033f5de)

**Comment by EmranMR** [comment]
> Instead of forking the repo and maintaining a separate copy of the original, the best thing to do would be to submit a PR to the original repo that splits into two different parsers, similar to the [markdown parser](https://github.com/MDeiml/tree-sitter-markdown) in which two parsers live in the same repo:
> 
> ![image](https://user-images.githubusercontent.com/4176520/248504443-fed1b4b8-1047-49d1-b08a-b0acf033f5de.png)

Very interesting @CalebDW.  Quick question 🤔, that doesn’t look like a submodule as well, are they maintaining two separate folders? 

PHP is ever growing so the main branch would be changing frequently as the new versions come out. Wouldn’t that mean duplicate work for writing new php grammars inside two separate folders? 

Now what I had in mind in terms of maintainability (which might not even be practical, as I am not really an expert in GitHub/git) was the following:

1) fork the branch, do all the necessary adjustment, changing the parser name and somehow remove the html injection  etc
2) The `tree-sitter-php` evolves on its own branch
3) whenever there is a new release we merge the main into the `phpbase` branch this way the php only version stays update meanwhile not doing any HTML injection etc.

**Comment by CalebDW** [comment]
@EmranMR,

No those are not submodules, and the common grammar between the two is in a folder the next level up. In the case of the PHP parser I've already [split them up](https://github.com/CalebDW/tree-sitter-php/tree/split_parsers) and will try to submit a draft PR to garner feedback from the project maintainers.

There's no duplicate work, the entire php grammer is in the `php-only` directory and the `php` grammer just parses the `text` and `php` sections and then injects those languages into the nodes

**Comment by EmranMR** [comment]
> @EmranMR,
> 
> No those are not submodules, and the common grammar between the two is in a folder the next level up. In the case of the PHP parser I've already [split them up](https://github.com/CalebDW/tree-sitter-php/tree/split_parsers) and will try to submit a draft PR to garner feedback from the project maintainers.
> 
> There's no duplicate work, the entire php grammer is in the `php-only` directory and the `php` grammer just parses the `text` and `php_only` sections and then injects those languages into the nodes

Oh wow, you have already done all the work  + the PR!! 🎉🎉 
Can’t wait to actually clone and try it out myself as well. Hopefully there are no issues and we get the merge soon 🤞 one of the roadblocks out the way, one step at a time.

**Comment by stormherz** [comment]
@calebdw sorry for bothering you about this. It seems like split parser support has landed (many thanks for that effort), but I wasn't able to verify it on my local setup (I'm the author of EmranMR/tree-sitter-blade#51). 

Judging from the code of `tree-sitter-blade`, I'm assuming treesitter won't build `php_only` parser right away during `:TSInstall`, since Makefile still uses `php` parser by default, is this correct or am I missing the plot entirely?

**Comment by calebdw** [comment]
@stormherz no need to be sorry! There's an [open PR](https://github.com/nvim-treesitter/nvim-treesitter/pull/5876) to add the needed configs so that nvim-treesitter knows about `php_only`, but until that is merged you could always [manually add it to treesitter](https://github.com/nvim-treesitter/nvim-treesitter?tab=readme-ov-file#adding-parsers)

**Comment by stormherz** [comment]
@calebdw thanks! totally forgot about that option. works like a charm, actually

**Comment by EmranMR** [comment]
@calebdw Amazing! thank you again for sorting that out!
